sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: linux
    dist: trusty
    env: VERSION=5
  - os: osx
    osx_image: xcode8
    language: generic
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition DocoptCpp
notifications:
  slack:
    secure: CrVwFwTxP/bF59PMKComeRrbYtzdANZPsGzlDBRnW2CPdGzs/ffWTcC55DGlPFpcEix3tRcb08MVDH2645hJAZIg/G+yTw24HB7zLz0m/86zrTEQaOhIC8HCvDDFS9G8KRj5dzugB75LmAuGFb2rir7JJLA/mL5clJvv7BocJLlXfsWxkpCcVi8GZwN28bcEyFoFhwzLjBHsfZuLQONrau/xiqnHhsTM2oepEt8+aHNmRML9xWMfB9MPIpQVXrVD7MJ58BsMP598AeGmiNoyygYUfNUhwz9lu2h47lX5Ex9sTMO5Gh3BUq6556hqJelbmBXMtq3jSfOtSXVmFSuLXQrzN10A37L4vdGFpu5AyAKc6nHLVi+QHOr9tKl7dAUrE48ciLea6QZ1MrJ8kZpGwrsUptmLRLYJUJc0w6BsKMfe90Ur61pDDD9bF/6lE+HHCVzpPZ1p2ASLA7CNFFHuZ2NhElxky6fBOJoeRgThRAaCNpuXppf1+ij/dz36hNDXP19Y8lGDgoNsz6FT7OV1l8TUharZFxIgQm3UEv2/UV3fnSI2OOGh70zOw2r8USmd+l7H+ReAUaF0dC11BDp3Vt79sM9+g9bHTGUdPUjURu2NOXIbKsAiXrSBijyyCU4R9Axy2me/zSZMHhK+hkzZz12JB+XVdULPL+Szr0GaggM=
