sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: osx
    osx_image: xcode9.2
    language: generic
global:
  env:
  - PROJECT=DocoptCpp
  - PROJECT_TEMPLATE=default
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition DocoptCpp
notifications:
  slack:
    secure: NMEIwbk8rAhz+8potxZwuBz2wHIzgCShLfK2AMewe7B2NsSWzwg2j8KKlj8GgNuGhg4jG34+RV1lnKHXAysOL4rRzivDtCXOX0xTBr7dfy2Tm5/oa2wAQl8VneI7kJRc1A2FS+KDi7wDUBCLDkbQy/Axn5CI8hp9G0jYL091X1a7LYpCF7L5K72qIFRmyofIbMrcEClwNb61RjWdvx9gjrRAueEEsHvsVbGFUsPgUCozWiKW5KcyztrzOOA1BUSF64z4bMCeAnasnFBH1fiEKowSN2/0xmagjiKlTiLy0ZRJ8tSWa/5XF6/lxV82DUIOF5gmGx7h4/dyEU67gxLUJqM4B7ghwN3zdx//XOeHaszGyWLUxBgfL4Yk1gPnMdml3s3gAt04YiBFfEVmj8EHZo7RZFrKgUumVt/Mk3hI+v/4g079XELmyPNKrx0vATSTwbS0Hy4jPomDtwfw/BBUvlNTa2aUFxNGhNyjc6GkmJ04BNCwrEU5WDavkX81EyA9LjbdAhlAPVvDP+nyJkU2uzixlvKt24/hhYBhE8ccnpSZoT8IYeApi9JbNIpSh8bYsoZn2cZqgTK5w4oGbT8zDFzi5iO4QkKxwdK90NsiHcFBPc439oLm7z5HFeSDbPL1mPcmGMlX6s673QMQxrHjazqCeKMxcQO/Y0lMq0PyJFA=
