sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty          
          env: VERSION=6
        - os: linux
          dist: trusty          
          env: VERSION=7
        - os: linux
          dist: trusty          
          env: VERSION=5
        # Use generic language for osx
        - os: osx
          osx_image: xcode8
          language: generic

install:
    - bash script/install-unix.sh
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
script:
    - bash script/travis-build.sh
notifications:
    slack:
        secure: "DLzyiRF2HyUvWjO8l8zWbBfP0q3hrRiQeAEQagPS1+i/WHF0b9iiR7zAk2RYzfJn2+gK4jIkG51GGhPIxHvAsxpsjxsm9uWDb7KE5iFoFQN2JASqy3tlayIZuKF09vdMJsrWafhQL+CSzlV8wZbkNchl70FvkQ8FKVEThQXv9FtZTJE1Df0fKCoOVkaEZMx9gA8bMIJKdTD1329rKKTiSH4EvtapjrHT8cYGfimrQAtAmt/rqOFJxyBpHyAsdXYf304CxNsp2qJKvWTDVlFWIxcwuUOJtWxKGFlhC44i97CO4Su6lsW9dE1uRmeFxOvn/bUqD8LJJuSFbeyCZlNEU+rS34rCBOLfV1SZK2uUtw4Ycjv5moTdcdxgYXPkI4mF6U1JXVUldIsdFuCZvxinyvFq1mY93YimC5Hk2MRCrGhfWRb5pQyXbTUHBQcGoa8RSRxtP/5+8IVeMCQr7s4oCw/bqaJvryIG2OV2wgNJrtLpi2D9ckoz3DlpdUCiLRWJhOVx3KYs4r1XgER3p3X9ptsfPFNgi2n3Y6UlSEYLTjgYPlaGy+uK9p1n4/tvU8qK0/r77E8w1fJwsiH4n5d8nSI4HujfT0FtSYaqzzLUDDt0Ukw87wbMwxyczy48+XjDe5ojpOJbVK16QOcl2U30Ugxi5iKaXMvCxgL6Z89AYAs="